/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export type { LSP8DropsDigitalAsset } from "./LSP8DropsDigitalAsset";
export * as factories from "./factories";
export { LSP8DropsDigitalAsset__factory } from "./factories/LSP8DropsDigitalAsset__factory";
